import {test,expect} from '@playwright/test';
import {mkdtemp,rm,mkdir,readFile,stat} from 'node:fs/promises';
import os from 'node:os';import path from 'node:path';
import {createApp} from '../../server/app.js';
import {seedInitialContent} from '../../server/seed.js';
let app,server,dir;
test.use({hasTouch:true});
test.beforeAll(async()=>{dir=await mkdtemp(path.join(os.tmpdir(),'pose-browser-'));app=createApp({dataDir:dir,publicOrigin:'http://127.0.0.1:4173',staticDir:path.resolve('dist')});await seedInitialContent(app.locals.db);server=await new Promise(resolve=>{const s=app.listen(4173,'127.0.0.1',()=>resolve(s));});await mkdir('_project_review/20260923-pose-upgrade',{recursive:true});});
test.afterAll(async()=>{await new Promise(resolve=>server.close(resolve));app.locals.close();await rm(dir,{recursive:true,force:true});});
const errors=new WeakMap();
test.beforeEach(async({page})=>{errors.set(page,[]);page.on('pageerror',error=>errors.get(page).push(error.message));await page.route('**/*',route=>{const url=route.request().url();if(/^https?:/.test(url)&&!url.startsWith('http://127.0.0.1:4173/')){errors.get(page).push(url);return route.abort();}return route.continue();});});
test.afterEach(async({page})=>expect(errors.get(page)).toEqual([]));
test('姿势样本真实提取、训练、预测、修改与重训',async({page,request})=>{
 test.setTimeout(180000);
 await page.goto('/labs/cv/teachable-machine');
 const lab=page.frameLocator('iframe');
 await expect(lab.locator('#train')).toBeDisabled();
 await lab.locator('#examples').click();
 await expect(lab.locator('#status')).toHaveText(/已载入两类姿势|示例加载失败/,{timeout:90000});
 await expect(lab.locator('.sample')).toHaveCount(24);
 await lab.locator('.advanced summary').click();await lab.locator('#epochs').fill('50');await lab.locator('#train').click();
 await expect(lab.locator('#status')).toHaveText('训练完成，可以测试姿势',{timeout:90000});
 await expect(lab.locator('.probability')).toHaveCount(2);
 const bars=lab.locator('.probability progress');
 const first=await bars.evaluateAll(items=>items.map(item=>item.value));
 expect(first.every(Number.isFinite)).toBe(true);expect(first.reduce((a,b)=>a+b,0)).toBeCloseTo(1,4);
 await lab.locator('.class-card').nth(1).locator('.sample img').first().click();
 await expect.poll(()=>bars.evaluateAll(items=>items.map(item=>item.value))).not.toEqual(first);
 await page.screenshot({path:'_project_review/20260923-pose-upgrade/pose-trained.png'});
 await lab.locator('main').screenshot({path:'public/lab-previews/teachable-machine.png'});
 const downloads=[];page.on('download',download=>downloads.push(download));await lab.locator('#export').click();
 await expect(lab.locator('#status')).toHaveText('已导出模型、权重和类别信息');
 await expect.poll(()=>downloads.length).toBe(3);
 const exported=new Map(await Promise.all(downloads.map(async download=>[download.suggestedFilename(),await download.path()])));
 expect([...exported.keys()].sort()).toEqual(['metadata.json','pose-model.json','pose-model.weights.bin']);
 const metadata=JSON.parse(await readFile(exported.get('metadata.json'),'utf8'));
 expect(metadata.labels).toEqual(['站立','下蹲']);
 const savedModel=JSON.parse(await readFile(exported.get('pose-model.json'),'utf8'));
 expect(savedModel.modelTopology).toBeTruthy();expect((await stat(exported.get('pose-model.weights.bin'))).size).toBeGreaterThan(0);
 const sampleData=await lab.locator('.sample img').first().getAttribute('src');
 const image=Buffer.from(sampleData.split(',')[1],'base64');
 await lab.locator('#test-image').setInputFiles({name:'pose.jpg',mimeType:'image/jpeg',buffer:image});
 await expect(lab.locator('#camera-status')).toHaveText('正在测试本机图片');
 await lab.getByRole('button',{name:'删除 站立 样本 1',exact:true}).click();
 await expect(lab.locator('.probability')).toHaveCount(0);await expect(lab.locator('#export')).toBeDisabled();
 await lab.locator('#add-class').click();await expect(lab.locator('#train')).toBeDisabled();
 await lab.locator('.class-card').last().getByRole('button',{name:'删除类别'}).click();
 await lab.getByLabel('类别 1 名称').fill('直立');await lab.getByLabel('类别 1 名称').press('Tab');
 await lab.locator('#epochs').fill('2');await lab.locator('#train').click();
 await expect(lab.locator('#status')).toHaveText('训练完成，可以测试姿势',{timeout:60000});
 await expect(lab.locator('.probability').first()).toContainText('直立');
 await lab.locator('#epochs').fill('100');await lab.locator('#train').click();await expect(lab.locator('#status')).toContainText(/训练 \d+ \/ 100/,{timeout:30000});await lab.locator('#stop-training').click();
 await expect(lab.locator('#status')).toHaveText('训练已停止，请重新训练',{timeout:30000});
 await lab.locator('#clear-all').click();await expect(lab.locator('.sample')).toHaveCount(0);
 await lab.locator('.class-card').first().locator('input[type=file]').setInputFiles({name:'pose.jpg',mimeType:'image/jpeg',buffer:image});
 await expect(lab.locator('.sample')).toHaveCount(1,{timeout:30000});
 expect((await request.get('/experiments/teachable/pose-model/model.json')).status()).toBe(200);
 expect((await request.get('/experiments/teachable/model/model.json')).status()).toBe(404);
 expect((await request.get('/experiments/tensorspace/examples/trainingLeNet/trainingLeNet.html')).status()).toBe(404);
});
test('姿势摄像头模拟视频、采样和迟到授权清理',async({page})=>{
 test.setTimeout(90000);
 await page.addInitScript(()=>{
  window.mockCamera={requests:[],tracks:[],delayed:false};
  navigator.mediaDevices.getUserMedia=async constraints=>{
   window.mockCamera.requests.push(constraints);
   const v=document.createElement('video');v.muted=true;v.loop=true;v.playsInline=true;
   await new Promise((resolve,reject)=>{v.onloadeddata=resolve;v.onerror=reject;v.src='/experiments/teachable/pose-samples/squats.mp4';});await v.play();
   const c=document.createElement('canvas');c.width=320;c.height=320;const ctx=c.getContext('2d');
   const paint=()=>{ctx.drawImage(v,0,0,320,320);};paint();const interval=setInterval(paint,50);
   const stream=c.captureStream(10);window.mockCamera.tracks.push(...stream.getTracks());
   stream.getTracks().forEach(track=>{const stop=track.stop.bind(track);track.stop=()=>{stop();clearInterval(interval);v.pause();v.removeAttribute('src');v.load();};});
   if(window.mockCamera.delayed)await new Promise(resolve=>window.resolveCamera=resolve);
   return stream;
  };
  navigator.mediaDevices.enumerateDevices=async()=>[{kind:'videoinput',deviceId:'simulated',label:'模拟相机'}];
 });
 await page.goto('/experiments/teachable/index.html');expect(await page.evaluate(()=>window.mockCamera.requests.length)).toBe(0);
 await page.locator('#camera').click();await expect(page.locator('#camera-status')).toContainText('已检测到姿势',{timeout:60000});
 await page.getByRole('button',{name:'拍一张',exact:true}).first().click();await expect(page.locator('.sample')).toHaveCount(1,{timeout:30000});
 const hold=page.getByRole('button',{name:'按住录制姿势',exact:true}).first();await hold.hover();await page.mouse.down();
 await expect(page.locator('.sample-label').first()).toContainText(/· [2-9] 个/,{timeout:30000});await page.mouse.up();await page.locator('#camera-stop').click();
 expect(await page.evaluate(()=>window.mockCamera.tracks.every(track=>track.readyState==='ended'))).toBe(true);
 await page.evaluate(()=>window.mockCamera.delayed=true);await page.locator('#camera').click();await expect.poll(()=>page.evaluate(()=>typeof window.resolveCamera)).toBe('function');await page.locator('#camera-stop').click();await page.evaluate(()=>window.resolveCamera());
 await expect.poll(()=>page.evaluate(()=>window.mockCamera.tracks.every(track=>track.readyState==='ended'))).toBe(true);
 expect(await page.evaluate(()=>window.mockCamera.requests.every(r=>r.audio===false))).toBe(true);
});
test('姿势模型缺失与相机拒绝可恢复',async({page})=>{
 await page.addInitScript(()=>{navigator.mediaDevices.getUserMedia=async()=>{throw new DOMException('权限被拒绝','NotAllowedError');};});
 await page.goto('/experiments/teachable/index.html');await page.locator('#camera').click();await expect(page.locator('#camera-status')).toContainText('权限被拒绝');
 await page.route('**/teachable/pose-model/model.json',route=>route.fulfill({status:404,body:'missing'}));
 await page.locator('#examples').click();await expect(page.locator('#status')).toContainText('示例加载失败',{timeout:30000});
 await expect(page.locator('#examples')).toBeEnabled();await expect(page.locator('#train')).toBeDisabled();await expect(page.locator('.sample')).toHaveCount(0);
});

