import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import ExcelJS from 'exceljs';
import { createApp } from '../server/app.js';
import { createAdmin, createSession } from '../server/auth.js';
import { parseNames, previewStudents } from '../server/students.js';
import { backupData, restoreData } from '../scripts/data-files.mjs';
import { openDatabase } from '../server/db.js';

test('student import, password gates, private learning files, submissions, resets and backup', async () => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'donghua-students-'));
  const dataDir = path.join(root, 'data');
  const origin = 'http://127.0.0.1';
  const app = createApp({ dataDir, publicOrigin: origin, secureCookies: false });
  const db = app.locals.db;
  const admin = createAdmin(db, 'test-admin', crypto.randomBytes(20).toString('hex'));
  const adminSession = createSession(db, admin.id);
  const server = await new Promise(resolve => { const instance = app.listen(0, '127.0.0.1', () => resolve(instance)); });
  const base = `http://127.0.0.1:${server.address().port}`;
  const adminClient = { cookie: `sid=${adminSession.id}`, csrf: adminSession.csrf_token };
  function client() { return { cookie: '', csrf: '' }; }
  async function api(c, route, method = 'GET', body) {
    const headers = { Origin: origin, Connection: 'close', Cookie: c.cookie, 'X-CSRF-Token': c.csrf };
    if (body && !(body instanceof FormData)) { headers['Content-Type'] = 'application/json'; body = JSON.stringify(body); }
    const response = await fetch(base + route, { method, headers, body });
    const cookie = response.headers.get('set-cookie'); if (cookie) c.cookie = cookie.split(';')[0];
    const result = (response.headers.get('content-type') || '').includes('application/json') ? await response.json() : Buffer.from(await response.arrayBuffer());
    if (result.csrfToken) c.csrf = result.csrfToken;
    return { status: response.status, body: result, headers: response.headers };
  }
  const pdf = Buffer.from('%PDF-1.4\n1 0 obj\n<< /Type /Catalog >>\nendobj\n%%EOF');
  const form = (name = '课程.pdf', bytes = pdf) => { const value = new FormData(); value.append('file', new Blob([bytes], { type: 'application/pdf' }), name); return value; };
  const login = async (c, username, password = username) => { await api(c, '/api/student/session'); return api(c, '/api/student/login', 'POST', { username, password }); };
  try {
    assert.deepEqual(await parseNames({ names: '张三，李四,王五\n赵六' }), ['张三', '李四', '王五', '赵六']);
    assert.deepEqual(await parseNames({}, { originalname: '名单.txt', buffer: Buffer.from('\uFEFF张三\r\n李四') }), ['张三', '李四']);
    const excel = new ExcelJS.Workbook(); excel.addWorksheet('学生').addRows([['姓名'], ['张三'], ['张三']]);
    const roster = await parseNames({}, { originalname: '名单.xlsx', buffer: await excel.xlsx.writeBuffer() });
    assert.deepEqual(roster, ['张三', '张三']);
    const preview = previewStudents(db, [...roster, '章三']);
    assert.deepEqual(preview.map(row => row.username), ['zhangsan', 'zhangsan2', 'zhangsan3']);
    assert.equal((await api(client(), '/api/admin/students')).status, 401);
    const imported = await api(adminClient, '/api/admin/students/import', 'POST', { students: preview });
    assert.equal(imported.status, 201);
    assert.equal((await api(adminClient, '/api/admin/students/import', 'POST', { students: preview })).status, 409);
    const a = client(), b = client(), anonymous = client();
    const first = await login(a, 'zhangsan'); assert.equal(first.status, 200); assert.equal(first.body.student.mustChangePassword, true);
    assert.match(first.headers.get('set-cookie'), /Max-Age=604800/u);
    assert.equal((await api(a, '/api/student/learning')).status, 403);
    assert.equal((await api(a, '/api/student/password', 'POST', { currentPassword: 'zhangsan', newPassword: 'short' })).status, 400);
    assert.equal((await api(a, '/api/student/password', 'POST', { currentPassword: 'zhangsan', newPassword: 'student-password-a' })).status, 200);
    assert.equal((await api(a, '/api/admin/students')).status, 401);
    await login(b, 'zhangsan2');
    await api(b, '/api/student/password', 'POST', { currentPassword: 'zhangsan2', newPassword: 'student-password-b' });
    assert.equal((await api(adminClient, '/api/admin/learning/files', 'POST', form('伪装.pdf', Buffer.from('<html>hello</html>')))).status, 400);
    assert.deepEqual(await fs.readdir(path.join(dataDir, 'uploads')), []);
    assert.equal((await api(adminClient, '/api/admin/learning/files?inline=1', 'POST', form())).status, 400);
    assert.deepEqual(await fs.readdir(path.join(dataDir, 'uploads')), []);
    const upload = await api(adminClient, '/api/admin/learning/files', 'POST', form()); assert.equal(upload.status, 201);
    const fileId = upload.body.id;
    const resource = await api(adminClient, '/api/admin/learning', 'POST', { kind: 'resource', title: '课堂资料', fileIds: [fileId] });
    assert.equal((await api(a, `/api/student/files/${fileId}`)).status, 404);
    await api(adminClient, `/api/admin/learning/${resource.body.id}/publish`, 'POST');
    assert.equal((await api(anonymous, `/api/student/files/${fileId}`)).status, 401);
    const download = await api(a, `/api/student/files/${fileId}`); assert.equal(download.status, 200); assert.deepEqual(download.body, pdf);
    assert.match(download.headers.get('cache-control'), /no-store/u);
    await api(adminClient, `/api/admin/learning/${resource.body.id}`, 'PUT', { title: '尚未发布的修改', fileIds: [] });
    assert.equal((await api(a, '/api/student/learning')).body[0].title, '课堂资料');
    const png = await fs.readFile('public/brand/dhu-emblem.png');
    const illustration = await api(adminClient, '/api/admin/learning/files', 'POST', form('配图.png', png));
    assert.equal(illustration.status, 201);
    const imageId = illustration.body.id;
    const blocks = [{ type: 'text', text: '观察图片并回答问题。' }, { type: 'image', fileId: imageId, caption: '课堂配图' }, { type: 'text', text: '请提交你的说明。' }];
    assert.equal((await api(adminClient, '/api/admin/learning', 'POST', { kind: 'assignment', title: '错误图片', blocks: [{ type: 'image', fileId }] })).status, 400);
    const assignment = await api(adminClient, '/api/admin/learning', 'POST', { kind: 'assignment', title: '第一次作业', blocks });
    const id = assignment.body.id;
    assert.equal((await api(a, `/api/student/files/${imageId}?view=1`)).status, 404);
    assert.equal((await api(a, `/api/student/assignments/${id}/submit`, 'POST', form())).status, 404);
    await api(adminClient, `/api/admin/learning/${id}/publish`, 'POST');
    assert.deepEqual((await api(a, '/api/student/learning')).body.find(row => row.id === id).blocks, blocks);
    const imageResponse = await api(a, `/api/student/files/${imageId}?view=1`);
    assert.equal(imageResponse.status, 200); assert.equal(imageResponse.headers.get('content-type'), 'image/png');
    assert.deepEqual(imageResponse.body, png);
    assert.equal((await api(anonymous, `/api/student/files/${imageId}?view=1`)).status, 401);
    await api(adminClient, `/api/admin/learning/${id}`, 'PUT', { title: '第一次作业', blocks: [{ type: 'text', text: '草稿修改' }] });
    assert.equal((await api(a, `/api/student/files/${imageId}?view=1`)).status, 200);
    await api(adminClient, `/api/admin/learning/${id}/publish`, 'POST');
    assert.equal((await api(a, `/api/student/files/${imageId}?view=1`)).status, 404);
    await api(adminClient, `/api/admin/learning/${id}`, 'PUT', { title: '第一次作业', blocks });
    await api(adminClient, `/api/admin/learning/${id}/publish`, 'POST');
    const submission = await api(a, `/api/student/assignments/${id}/submit`, 'POST', form('作业.pdf')); assert.equal(submission.status, 201);
    assert.equal((await api(b, `/api/student/files/${submission.body.file.id}`)).status, 404);
    assert.equal((await api(a, `/api/student/files/${submission.body.file.id}`)).status, 200);
    assert.equal((await api(adminClient, `/api/admin/learning/files/${submission.body.file.id}`)).status, 200);
    const second = await api(a, `/api/student/assignments/${id}/submit`, 'POST', form('新作业.pdf')); assert.equal(second.status, 201);
    const report = await api(adminClient, `/api/admin/learning/${id}/submissions`);
    assert.equal(report.body.length, 3); assert.equal(report.body.filter(row => row.file).length, 1);
    assert.equal(report.body.find(row => row.username === 'zhangsan').file.name, '新作业.pdf');
    assert.equal((await api(a, `/api/student/files/${submission.body.file.id}`)).status, 404);
    await api(adminClient, `/api/admin/learning/${id}/unpublish`, 'POST');
    assert.equal((await api(a, `/api/student/files/${imageId}?view=1`)).status, 404);
    await api(adminClient, `/api/admin/learning/${id}/publish`, 'POST');
    await api(adminClient, `/api/admin/learning/${resource.body.id}/unpublish`, 'POST');
    assert.equal((await api(a, `/api/student/files/${fileId}`)).status, 404);
    await api(adminClient, `/api/admin/students/${imported.body[0].id}/reset-password`, 'POST');
    assert.equal((await api(a, '/api/student/learning')).status, 401);
    assert.equal((await login(a, 'zhangsan', 'student-password-a')).status, 401);
    assert.equal((await login(a, 'zhangsan')).body.student.mustChangePassword, true);
    assert.equal((await api(a, `/api/student/files/${second.body.file.id}`)).status, 403);
    await api(adminClient, `/api/admin/students/${imported.body[1].id}`, 'PUT', { active: false });
    assert.equal((await api(b, '/api/student/learning')).status, 401);
    assert.equal((await login(b, 'zhangsan2', 'student-password-b')).status, 401);
    const invalidCsrf = { ...adminClient, csrf: 'wrong' };
    assert.equal((await api(invalidCsrf, '/api/admin/students/import', 'POST', { students: preview })).status, 403);
    await new Promise(resolve => server.close(resolve)); app.locals.close();
    const backup = path.join(root, 'backup'), restored = path.join(root, 'restored');
    await backupData(dataDir, backup); await restoreData(backup, restored);
    const restoredDb = openDatabase(restored);
    assert.equal(restoredDb.prepare('SELECT count(*) n FROM students').get().n, 3);
    assert.equal(restoredDb.prepare('SELECT count(*) n FROM student_sessions').get().n, 0);
    assert.equal(restoredDb.prepare('SELECT count(*) n FROM homework_submissions').get().n, 1);
    const savedFile = restoredDb.prepare('SELECT storage_name FROM learning_files WHERE id=?').get(second.body.file.id);
    assert.deepEqual(await fs.readFile(path.join(restored, 'media', savedFile.storage_name)), pdf); restoredDb.close();
  } finally {
    if (server.listening) await new Promise(resolve => server.close(resolve));
    app.locals.close(); await fs.rm(root, { recursive: true, force: true });
  }
});
